//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FairfieldTekLLC.Tiny.Udp.Server.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FairfieldTekLLC.Tiny.Udp.Server.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding Client Endpoint {0}.
        /// </summary>
        internal static string Message_AddingEndpoint {
            get {
                return ResourceManager.GetString("Message_AddingEndpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removing Client Endpoint {0}.
        /// </summary>
        internal static string Message_ClientRemoved {
            get {
                return ResourceManager.GetString("Message_ClientRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - Missed Ping. {1} != {2}.
        /// </summary>
        internal static string Message_MissedPing {
            get {
                return ResourceManager.GetString("Message_MissedPing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Datagram Controller for Datagram Type {0}.
        /// </summary>
        internal static string Message_NoHandler {
            get {
                return ResourceManager.GetString("Message_NoHandler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ping  from {0} Check Value:  {1}.
        /// </summary>
        internal static string Message_Ping {
            get {
                return ResourceManager.GetString("Message_Ping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ping Delay {0} ms..
        /// </summary>
        internal static string Message_PingDelay {
            get {
                return ResourceManager.GetString("Message_PingDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiny Udp Server starting on port {0}..
        /// </summary>
        internal static string Message_ServerStarted {
            get {
                return ResourceManager.GetString("Message_ServerStarted", resourceCulture);
            }
        }
    }
}
